# Generated by Django 5.2.2 on 2026-01-09 11:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Conductor', 'Conductor'), ('Visualizador', 'Visualizador')], default='Visualizador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='CuentaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 22.06.002.001', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Ej: Mantenimiento y Reparación de Vehículos', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cuenta Presupuestaria (SIGFE)',
                'verbose_name_plural': 'Cuentas Presupuestarias',
                'db_table': 'cuenta_presupuestaria',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('nombre_fantasia', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('es_taller', models.BooleanField(default=False, verbose_name='Es Taller Mecánico')),
                ('es_arrendador', models.BooleanField(default=False, verbose_name='Es Arrendador de Vehículos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('nro_motor', models.CharField(blank=True, max_length=50)),
                ('anio_adquisicion', models.IntegerField()),
                ('vida_util', models.IntegerField(default=10, help_text='Años de vida útil estimada')),
                ('kilometraje_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('umbral_mantencion', models.IntegerField(default=10000, help_text='Kms entre mantenciones preventivas')),
                ('tipo_carroceria', models.CharField(choices=[('Ambulancia', 'Ambulancia'), ('Sedán', 'Sedán'), ('Station Vagon', 'Station Vagon'), ('Camioneta', 'Camioneta'), ('Minibús', 'Minibús'), ('Furgón', 'Furgón'), ('Camión', 'Camión'), ('Carro de Arrastre', 'Carro de Arrastre')], max_length=20)),
                ('clase_ambulancia', models.CharField(blank=True, choices=[('URBANA (4X2)', 'URBANA (4X2)'), ('TODO TERRENO (4X4)', 'TODO TERRENO (4X4)'), ('MARÍTIMO (LANCHA)', 'MARÍTIMO (LANCHA)')], max_length=50, null=True, verbose_name='Clase Ambulancia')),
                ('es_samu', models.BooleanField(default=False, verbose_name='Pertenece a SAMU')),
                ('establecimiento', models.CharField(default='Hospital Río Negro', max_length=200)),
                ('criticidad', models.CharField(choices=[('Crítico', 'Crítico'), ('No crítico', 'No crítico')], default='No crítico', max_length=20)),
                ('es_backup', models.BooleanField(default=False, verbose_name='¿Es vehículo de backup?')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso'), ('En mantenimiento', 'En mantenimiento'), ('Fuera de servicio', 'Fuera de servicio'), ('Baja', 'Dado de Baja')], default='Disponible', max_length=20)),
                ('tipo_propiedad', models.CharField(choices=[('Propio', 'Propio'), ('Arrendado', 'Arrendado (Reemplazo)')], default='Propio', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_oc', models.CharField(max_length=50, unique=True, verbose_name='Nro Orden de Compra')),
                ('fecha_emision', models.DateField()),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('id_licitacion', models.CharField(blank=True, max_length=50, verbose_name='ID MercadoPúblico')),
                ('folio_sigfe', models.CharField(blank=True, max_length=50, verbose_name='Folio SIGFE')),
                ('estado', models.CharField(choices=[('Emitida', 'Emitida'), ('Aceptada', 'Aceptada'), ('Recepcionada', 'Recepcionada'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], default='Emitida', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='ordenes_compra/', verbose_name='PDF Orden de Compra')),
                ('cuenta_presupuestaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='flota.cuentapresupuestaria')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Ordenes de Compra',
                'db_table': 'orden_compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_ot', models.CharField(max_length=50, unique=True, verbose_name='Nro Orden de Trabajo')),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo solicitado')),
                ('fecha_solicitud', models.DateField()),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='flota.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='flota.proveedor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
                'db_table': 'orden_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(verbose_name='Año Presupuestario')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='flota.cuentapresupuestaria', verbose_name='Cuenta SIGFE')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuesto',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='flota.presupuesto', verbose_name='Presupuesto asociado'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='flota.proveedor'),
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantencion', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_programada', models.DateField(blank=True, help_text='Fecha en que se programó realizar el mantenimiento (para alertas por tiempo)', null=True, verbose_name='Fecha Programada')),
                ('km_al_ingreso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_trabajo', models.TextField()),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En taller', 'En taller'), ('Esperando repuestos', 'Esperando repuestos'), ('Finalizado', 'Finalizado / Cerrado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=30)),
                ('nro_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='mantenimientos/', verbose_name='Documento Adjunto')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Costo aproximado inicial', max_digits=12)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Mano de Obra')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Repuestos')),
                ('costo_total_real', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Final Total')),
                ('cuenta_presupuestaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.cuentapresupuestaria')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_directos', to='flota.ordencompra')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='flota.ordentrabajo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='flota.proveedor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('08-20', 'Turno 08:00 a 20:00'), ('20-08', 'Turno 20:00 a 08:00'), ('09-20', 'Turno 09:00 a 20:00 (fin de semana/feriado)')], max_length=20)),
                ('km_inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('km_fin', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('litros_inicio', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('litros_fin', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Hoja de Ruta',
                'verbose_name_plural': 'Hojas de Ruta',
                'db_table': 'hoja_ruta',
            },
        ),
        migrations.CreateModel(
            name='FallaReportada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField()),
                ('descripcion', models.TextField()),
                ('nivel_urgencia', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallas_reportadas', to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_origen', to='flota.mantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas_reportadas', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Falla Reportada',
                'verbose_name_plural': 'Fallas Reportadas',
                'db_table': 'falla_reportada',
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kilometraje_al_cargar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nro_boleta', models.CharField(blank=True, max_length=50)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to=settings.AUTH_USER_MODEL)),
                ('cuenta_presupuestaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.cuentapresupuestaria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='flota.proveedor')),
                ('patente_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'db_table': 'carga_combustible',
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente_arrendada', models.CharField(max_length=10, verbose_name='Patente vehículo arrendado')),
                ('marca_modelo_arrendado', models.CharField(max_length=100, verbose_name='Marca/Modelo arrendado')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('costo_diario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo total facturado')),
                ('motivo', models.TextField(help_text='Ej: Ambulancia HR-PG-25 en pana de motor - Estimado 15 días en taller')),
                ('nro_orden_compra', models.CharField(blank=True, max_length=50, verbose_name='N° Orden de Compra')),
                ('nro_factura', models.CharField(blank=True, max_length=50, verbose_name='N° Factura')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20)),
                ('dias_arriendo', models.IntegerField(default=0, verbose_name='Días de arriendo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='flota.proveedor')),
                ('vehiculo_reemplazado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriendos_sustitutos', to='flota.vehiculo', verbose_name='Vehículo propio reemplazado')),
            ],
            options={
                'verbose_name': 'Arriendo de Vehículo',
                'verbose_name_plural': 'Arriendos de Vehículos',
                'db_table': 'arriendo',
            },
        ),
        migrations.CreateModel(
            name='AlertaMantencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('valor_umbral', models.IntegerField()),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mantencion', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Alerta de Mantenimiento',
                'verbose_name_plural': 'Alertas de Mantenimiento',
                'db_table': 'alerta_mantencion',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('destino', models.CharField(max_length=200)),
                ('rut_paciente', models.CharField(blank=True, max_length=12)),
                ('nombre_paciente', models.CharField(blank=True, max_length=150)),
                ('tipo_servicio', models.CharField(choices=[('Traslado Paciente', 'Traslado Paciente'), ('Administrativo', 'Administrativo'), ('Urgencia SAMU', 'Urgencia SAMU'), ('Ronda Médica', 'Ronda Médica'), ('Otro', 'Otro')], default='Traslado Paciente', max_length=30)),
                ('km_recorridos_viaje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='flota.hojaruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'viaje',
            },
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['folio_sigfe'], name='orden_compr_folio_s_ebd1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado', 'fecha_emision'], name='orden_compr_estado_f6f846_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor', 'fecha_emision'], name='orden_compr_proveed_7d11e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together={('anio', 'vehiculo', 'cuenta')},
        ),
    ]
