# Generated by Django 5.2.2 on 2025-12-15 06:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Conductor', 'Conductor'), ('Visualizador', 'Visualizador')], default='Visualizador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_oc', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('id_licitacion', models.CharField(blank=True, max_length=50)),
                ('folio_sigfe', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Ordenes de Compra',
                'db_table': 'orden_compra',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('nombre_fantasia', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_ot', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_programada', models.DateField()),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='flota.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='flota.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
                'db_table': 'orden_trabajo',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='flota.proveedor'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('nro_motor', models.CharField(blank=True, max_length=50)),
                ('anio_adquisicion', models.IntegerField()),
                ('vida_util', models.IntegerField(default=10)),
                ('vida_util_residual', models.IntegerField(default=0)),
                ('kilometraje_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('umbral_mantencion', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_carroceria', models.CharField(choices=[('Ambulancia', 'Ambulancia'), ('Camioneta', 'Camioneta'), ('Otro', 'Otro')], max_length=20)),
                ('clase_ambulancia', models.CharField(blank=True, max_length=50)),
                ('es_samu', models.BooleanField(default=False)),
                ('establecimiento', models.CharField(default='Hospital Río Negro', max_length=200)),
                ('criticidad', models.CharField(choices=[('Crítico', 'Crítico'), ('No crítico', 'No crítico')], default='No crítico', max_length=20)),
                ('es_backup', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso'), ('En mantenimiento', 'En mantenimiento'), ('Fuera de servicio', 'Fuera de servicio'), ('Arrendado', 'Arrendado')], default='Disponible', max_length=20)),
                ('tipo_propiedad', models.CharField(choices=[('Propio', 'Propio'), ('Arrendado', 'Arrendado')], default='Propio', max_length=20)),
                ('dias_fuera_servicio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_oc', to='flota.ordencompra')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_ot', to='flota.ordentrabajo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='flota.proveedor')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='flota.vehiculo'),
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mantencion', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('km_al_ingreso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En taller', 'En taller'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=20)),
                ('dias_fuera_servicio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='flota.ordencompra')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='flota.ordentrabajo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='flota.proveedor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20)),
                ('km_inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('km_fin', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('litros_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('litros_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_ruta', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Hoja de Ruta',
                'verbose_name_plural': 'Hojas de Ruta',
                'db_table': 'hoja_ruta',
            },
        ),
        migrations.CreateModel(
            name='FallaReportada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField()),
                ('descripcion', models.TextField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallas_reportadas', to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas', to='flota.mantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas_reportadas', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Falla Reportada',
                'verbose_name_plural': 'Fallas Reportadas',
                'db_table': 'falla_reportada',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('dias_no_operativo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Vehículo',
                'verbose_name_plural': 'Disponibilidades de Vehículos',
                'db_table': 'disponibilidad_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('kilometraje_al_cargar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nro_boleta', models.CharField(blank=True, max_length=50)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to=settings.AUTH_USER_MODEL)),
                ('hoja_ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_combustible', to='flota.hojaruta')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='flota.proveedor')),
                ('patente_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'db_table': 'carga_combustible',
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('costo_diario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nro_orden_compra', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='flota.proveedor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriendos', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
                'db_table': 'arriendo',
            },
        ),
        migrations.CreateModel(
            name='AlertaMantencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('valor_umbral', models.IntegerField()),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='flota.mantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mantencion', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Alerta de Mantenimiento',
                'verbose_name_plural': 'Alertas de Mantenimiento',
                'db_table': 'alerta_mantencion',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('destino', models.CharField(max_length=200)),
                ('rut_paciente', models.CharField(blank=True, max_length=12)),
                ('tipo_servicio', models.CharField(choices=[('Traslado', 'Traslado'), ('Emergencia', 'Emergencia'), ('Otro', 'Otro')], default='Traslado', max_length=20)),
                ('km_recorridos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hoja_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='flota.hojaruta')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'viaje',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('subasignacion_sigfe', models.CharField(max_length=50)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuesto',
                'unique_together': {('anio', 'vehiculo', 'categoria')},
            },
        ),
    ]
