# Generated by Django 5.2.2 on 2026-02-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaruta',
            name='sin_camillero',
            field=models.BooleanField(default=False, verbose_name='No aplica camillero'),
        ),
        migrations.AddField(
            model_name='hojaruta',
            name='sin_enfermero',
            field=models.BooleanField(default=False, verbose_name='No va enfermero/matrón'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='direccion_especifica',
            field=models.CharField(blank=True, max_length=300, verbose_name='Alta a Domicilio'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_llegada_destino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Llegada a Destino'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_salida_destino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida de Destino'),
        ),
        migrations.AddField(
            model_name='viajepaciente',
            name='tipo_servicio',
            field=models.CharField(choices=[('Llamado', 'Llamado'), ('Rescate de Paciente', 'Rescate de Paciente'), ('A Urgencia HBO', 'A Urgencia HBO'), ('Otros', 'Otros (hora esp, imagen, etc)'), ('Exámenes', 'Exámenes'), ('Alta a Domicilio', 'Alta a Domicilio')], default='Urgencia', max_length=50, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='medico',
            field=models.CharField(max_length=150, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='hojaruta',
            name='tens',
            field=models.CharField(max_length=150, verbose_name='TENS'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.CharField(choices=[('Hospital Base Osorno', 'Hospital Base Osorno'), ('Domicilio', 'Domicilio (Requiere Dirección)')], default='Hospital Base Osorno', max_length=200),
        ),
        migrations.AlterField(
            model_name='viajepaciente',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
