# Generated by Django 5.2.2 on 2026-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='alerta_presupuesto_ignorada',
            field=models.BooleanField(default=False, verbose_name='Alerta de ejecución descartada'),
        ),
    ]
