# Generated by Django 5.2.2 on 2026-01-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='tipo_adquisicion',
            field=models.CharField(choices=[('Convenio Marco', 'Convenio Marco'), ('Licitación Pública', 'Licitación Pública'), ('Trato Directo', 'Trato Directo'), ('Compra Ágil', 'Compra Ágil')], default='Convenio Marco', max_length=30),
        ),
    ]
