# Generated by Django 5.2.2 on 2025-12-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='flota.presupuesto', verbose_name='Presupuesto asociado'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['folio_sigfe'], name='orden_compr_folio_s_ebd1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado', 'fecha_emision'], name='orden_compr_estado_f6f846_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['proveedor', 'fecha_emision'], name='orden_compr_proveed_7d11e2_idx'),
        ),
    ]
