# Generated by Django 5.2.2 on 2025-12-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='anio_fabricacion',
        ),
    ]
