# Generated by Django 5.2.2 on 2026-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_presupuesto_activo_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='clase_ambulancia',
            field=models.CharField(blank=True, choices=[('URBANA (4X2)', 'URBANA (4X2)'), ('TODO TERRENO (4X4)', 'TODO TERRENO (4X4)'), ('MARÍTIMO (LANCHA)', 'MARÍTIMO (LANCHA)')], max_length=50, null=True, verbose_name='Clase Ambulancia'),
        ),
    ]
