# Generated by Django 5.2.2 on 2026-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_hojaruta_sin_camillero_hojaruta_sin_enfermero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaruta',
            name='camillero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='enfermero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='sin_camillero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='sin_enfermero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='tens',
        ),
        migrations.AddField(
            model_name='viaje',
            name='camillero',
            field=models.CharField(blank=True, max_length=150, verbose_name='Camillero'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='enfermero',
            field=models.CharField(blank=True, max_length=150, verbose_name='Enfermero/a'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='medico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='sin_camillero',
            field=models.BooleanField(default=False, verbose_name='No aplica camillero'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='sin_enfermero',
            field=models.BooleanField(default=False, verbose_name='No va enfermero/matrón'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tens',
            field=models.CharField(blank=True, max_length=150, verbose_name='TENS'),
        ),
    ]
