# Generated by Django 5.2.2 on 2026-06-11 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_presupuesto_alerta_ignorada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaruta',
            name='camillero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='enfermero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='medico_derivador',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='no_aplica_camillero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='no_aplica_enfermero',
        ),
        migrations.RemoveField(
            model_name='hojaruta',
            name='tens',
        ),
        migrations.AddField(
            model_name='viaje',
            name='no_aplica_camillero',
            field=models.BooleanField(default=False, verbose_name='No aplica Camillero'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='no_aplica_enfermero',
            field=models.BooleanField(default=False, verbose_name='No aplica Enfermero'),
        ),
        migrations.CreateModel(
            name='PersonaTripulacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('MEDICO', 'Médico'), ('TENS', 'TENS'), ('ENFERMERO', 'Enfermero/Matrón'), ('CAMILLERO', 'Camillero')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Persona de tripulación',
                'verbose_name_plural': 'Personas de tripulación',
                'db_table': 'persona_tripulacion',
                'ordering': ['rol', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'rol'), name='uniq_persona_tripulacion_nombre_rol')],
            },
        ),
        migrations.CreateModel(
            name='TripulacionViaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('MEDICO', 'Médico'), ('TENS', 'TENS'), ('ENFERMERO', 'Enfermero/Matrón'), ('CAMILLERO', 'Camillero')], max_length=20)),
                ('persona_tripulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='flota.personatripulacion', verbose_name='Persona (de listado anterior)')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripulacion', to='flota.viaje')),
            ],
            options={
                'verbose_name': 'Tripulación de viaje',
                'verbose_name_plural': 'Tripulación de viajes',
                'db_table': 'tripulacion_viaje',
                'ordering': ['rol', 'id'],
            },
        ),
    ]
