# Generated by Django 5.2.2 on 2026-06-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_tripulacion_por_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='no_aplica_camillero',
            field=models.BooleanField(default=True, verbose_name='No aplica Camillero'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='no_aplica_enfermero',
            field=models.BooleanField(default=True, verbose_name='No aplica Enfermero'),
        ),
    ]
