"""Reexportación de vistas para `gestion_flota.urls`."""

from .utilidades import (
    es_administrador,
    es_conductor,
    es_conductor_o_admin,
    es_visualizador,
    puede_escribir,
    verificar_presupuesto_cuenta,
    rechazar_escritura_visualizador,
)
from .autenticacion import login_view, logout_view
from .usuarios import (
    registrar_usuario,
    listar_usuarios,
    modificar_usuario,
    deshabilitar_usuario,
)
from .vehiculos import (
    registrar_vehiculo,
    listar_flota,
    ficha_vehiculo,
    modificar_vehiculo,
    actualizar_estado_vehiculo,
    disponibilidad_flota,
    costo_por_kilometro,
    gastos_mantenimientos,
    alertas,
)
from .viajes import (
    registrar_bitacora,
    listar_bitacoras,
    modificar_bitacora,
    detalle_bitacora,
    registrar_carga_combustible,
    listar_cargas_combustible,
    registrar_incidente,
    listar_incidentes,
    historial_conductor,
    reabrir_bitacora,
    exportar_consolidado_viajes,
    exportar_traslados_form,
    agregar_viaje,
    acceso_bitacora,
    cerrar_hoja_ruta,
)
from .mantenimiento import (
    programar_mantenimiento,
    listar_mantenimientos,
    cambiar_estado_mantenimiento,
    editar_mantenimiento,
    finalizar_mantenimiento,
    eliminar_mantenimiento,
    calendario_mantenciones,
    api_mantenimientos,
)
from .panel_control import panel_control
from .presupuesto import (
    registrar_presupuesto,
    modificar_presupuesto,
    deshabilitar_presupuesto,
    listar_presupuestos,
)
from .reportes import (
    reportes,
    reporte_disponibilidad,
    reporte_historial_unidad,
)
from .arriendos import (
    listar_arriendos,
    registrar_arriendo,
    finalizar_arriendo,
    deshabilitar_arriendo,
    habilitar_arriendo,
)
from .dashboard import dashboard
from .proveedores import (
    listar_proveedores,
    registrar_proveedor,
    modificar_proveedor,
    habilitar_proveedor,
    deshabilitar_proveedor,
)
from .ordenes import (
    importar_orden_compra,
    registrar_orden_compra,
    listar_ordenes_compra,
    modificar_orden_compra,
    eliminar_orden_compra,
    detalle_orden_compra,
    registrar_orden_trabajo,
    listar_ordenes_trabajo,
    detalle_orden_trabajo,
    modificar_orden_trabajo,
    eliminar_orden_trabajo,
    api_orden_trabajo,
)
from .api import (
    api_vehiculos_kilometraje,
    api_alertas_count,
    api_verificar_presupuesto,
)

__all__ = [
    'es_administrador',
    'es_conductor',
    'es_conductor_o_admin',
    'es_visualizador',
    'puede_escribir',
    'verificar_presupuesto_cuenta',
    'rechazar_escritura_visualizador',
    'login_view',
    'logout_view',
    'registrar_usuario',
    'listar_usuarios',
    'modificar_usuario',
    'deshabilitar_usuario',
    'registrar_vehiculo',
    'listar_flota',
    'ficha_vehiculo',
    'modificar_vehiculo',
    'actualizar_estado_vehiculo',
    'disponibilidad_flota',
    'costo_por_kilometro',
    'gastos_mantenimientos',
    'alertas',
    'registrar_bitacora',
    'listar_bitacoras',
    'modificar_bitacora',
    'detalle_bitacora',
    'registrar_carga_combustible',
    'listar_cargas_combustible',
    'registrar_incidente',
    'listar_incidentes',
    'historial_conductor',
    'reabrir_bitacora',
    'exportar_consolidado_viajes',
    'exportar_traslados_form',
    'agregar_viaje',
    'acceso_bitacora',
    'cerrar_hoja_ruta',
    'programar_mantenimiento',
    'listar_mantenimientos',
    'cambiar_estado_mantenimiento',
    'editar_mantenimiento',
    'finalizar_mantenimiento',
    'eliminar_mantenimiento',
    'calendario_mantenciones',
    'api_mantenimientos',
    'panel_control',
    'registrar_presupuesto',
    'modificar_presupuesto',
    'deshabilitar_presupuesto',
    'listar_presupuestos',
    'reportes',
    'reporte_disponibilidad',
    'reporte_historial_unidad',
    'registrar_arriendo',
    'listar_arriendos',
    'finalizar_arriendo',
    'deshabilitar_arriendo',
    'habilitar_arriendo',
    'dashboard',
    'listar_proveedores',
    'registrar_proveedor',
    'modificar_proveedor',
    'habilitar_proveedor',
    'deshabilitar_proveedor',
    'importar_orden_compra',
    'registrar_orden_compra',
    'listar_ordenes_compra',
    'modificar_orden_compra',
    'eliminar_orden_compra',
    'detalle_orden_compra',
    'registrar_orden_trabajo',
    'listar_ordenes_trabajo',
    'detalle_orden_trabajo',
    'modificar_orden_trabajo',
    'eliminar_orden_trabajo',
    'api_orden_trabajo',
    'api_vehiculos_kilometraje',
    'api_alertas_count',
    'api_verificar_presupuesto',
]
